### ISSUE TITLE
Support downstream roundTripTimeoutSeconds for combined read and write of request, including upstream time.

### ISSUE THREAD

**Issue by simonmittag** [simonmittag/jabba#46]
**Is your feature request related to a problem? Please describe.**
Jabba needs a timeout for downstream roundtrip that covers downstream request, response time, including times waiting for upstream.

**Describe the solution you'd like**
connection.downstream.roudTripTimeoutSeconds should terminate connected sockets between user agent and Jabba  even if they're still writing in progress. It should also manage resources on the server for timed out requests.

the server should send the appropriate response code, between 200 OK (upstream response copy), 502 for upstream errors outside of timeout, 504 for upstream or downstream timeout errors.

## See
Timeout Handlers, context cancellation in golang: https://ieftimov.com/post/make-resilient-golang-net-http-servers-using-timeouts-deadlines-context-cancellation/

## Tasks on timeout
- [x] return early from running proxyHandler function once timeouts fire so downstream HTTP client gets an answer.
- [x] prevent retries once downstream timeout fired
- [x] prevent attempt to send response && logging of INF success by proxyHandler once downstream roundtrip timeout fired. instead log aborted request due to abort/timeout, with PATH, X-REQUEST-ID from nested Proxy struct
- [x] don't wait for upstream timeout if > roundtrip timeout to conserve resources.
- [x] fix the channel bug, where an already closed channel dies.
- [x] race condition with next attempt. fix the slowbody test on J1:8080. it exits too early with 200 instead of 502. cannot locally reproduce.
- [x] if http client fires an downstream timeout LOCALLY use 504 instead of 502 
- [x] globally replace 503 with 504 by re-implementing timeouthandler
- [x] if downstream timeout fires before upstream timeout, call cancel on the upstream attempt directly. you have to pass around the cancel method to do this.
- [x] implement integration tests for slowheader and slowbody with retries and timers to cover scenarios for 2, 4, 25, 31 seconds delay against Jabba1 and Jabba2 for a total of 8 test cases. validate status codes and response time.
- [x] send a custom HTTP response instead of normal response after timeout fires
- [x] implement integration tests to verify 503 is sent after timeout fires
- [x] implement integration test to verify connection is terminated after timeout fires

**Comment by simonmittag** [comment]
i need two separate jabba configs for the integration test here. 

## Test downstream roundTripTimeoutSeconds
one where downstream roundTripTimeoutSeconds is < upstream readTimeoutSeconds so I can test downstream roundTripTimout fires.

## Test upstream readTimeoutSeconds
downstream roundTripTimeoutSeconds > upstream readTimeoutSeconds so I can test upstream readTimeoutSeconds fires.
